import SectionTitle from "../../components/SectionTitle";
import { motion } from "framer-motion";

const Stats = () => {
  const container = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } },
  };
  const item = {
    hidden: { opacity: 0, y: 16 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.45, ease: "easeOut" } },
  };
  return (
    <div className="bg-gray-50 dark:bg-black dark:bg-opacity-10 p- min-h-[350px] flex flex-col py-6 px-4 items-center justify-center">
      <div className="w-full mb-5">
        <SectionTitle title="Our Achievements" />
      </div>
      <motion.div
        className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12 max-w-7xl"
        variants={container}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.2 }}
      >
        <motion.div className="text-center" variants={item}>
          <h3 className="text-gray-800 dark:text-secondary text-4xl font-extrabold">
            5.4<span className="text-blue-600">M+</span>
          </h3>
          <p className="text-base font-bold mt-4">Total Users</p>
          <p className="text-sm text-gray-500 mt-2">
            The total number of registered users on the platform.
          </p>
        </motion.div>
        <motion.div className="text-center" variants={item}>
          <h3 className="text-gray-800 dark:text-secondary text-4xl font-extrabold">
            $80<span className="text-blue-600">K</span>
          </h3>
          <p className="text-base font-bold mt-4">Revenue</p>
          <p className="text-sm text-gray-500 mt-2">
            The total revenue generated by the application.
          </p>
        </motion.div>
        <motion.div className="text-center" variants={item}>
          <h3 className="text-gray-800 dark:text-secondary text-4xl font-extrabold">
            100<span className="text-blue-600">K</span>
          </h3>
          <p className="text-base font-bold mt-4">Engagement</p>
          <p className="text-sm text-gray-500 mt-2">
            The level of user engagement with the application&apos;s content and
            features.
          </p>
        </motion.div>
        <motion.div className="text-center" variants={item}>
          <h3 className="text-gray-800 dark:text-secondary text-4xl font-extrabold">
            99.9<span className="text-blue-600">%</span>
          </h3>
          <p className="text-base font-bold mt-4">Server Uptime</p>
          <p className="text-sm text-gray-500 mt-2">
            The percentage of time the server has been operational and
            available.
          </p>
        </motion.div>
      </motion.div>
    </div>
  );
};

export default Stats;
